
trigger:
- none

variables:
- group: firebase-distribution

pool:
  vmImage: 'macos-latest'

steps:
- task: DownloadSecureFile@1
  name: googleServices
  inputs:
    secureFile: google-services.json
  displayName: Download google-services.json

- task: DownloadSecureFile@1
  name: Keystore
  inputs:
    secureFile: mobiletech-upload-keystore.jks
  displayName: Download keystore

- script: |
    echo Moving $(googleServices.secureFilePath) to the project location...
    mv $(googleServices.secureFilePath) $(Build.SourcesDirectory)/technician/
  displayName: Move google-service.json to sources directory

- task: JavaToolInstaller@0
  inputs:
    versionSpec: '11'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'PreInstalled'
  displayName: 'Install java'


- task: Gradle@2
  inputs:
    workingDirectory: ''
    gradleWrapperFile: 'gradlew'
    gradleOptions: '-Xmx3072m'
    publishJUnitResults: false
    testResultsFiles: '**/TEST-*.xml'
    tasks: ':technician:bundleBetaRelease'
  displayName: 'Generate aab'

- task: CmdLine@2
  inputs:
    script: >
      ls -la $(system.defaultworkingdirectory)/technician/build/outputs/bundle/betaRelease
  displayName: 'Print output directory '
- task: CmdLine@2
  inputs:
    script: >
      jarsigner -verbose -sigalg SHA256withRSA -digestalg SHA-256 
      -keystore $(Keystore.secureFilePath) 
      -storepass $(KEY_STORE_PASSWORD) 
      -keypass $(KEY_PASSWORD) 
      $(system.defaultworkingdirectory)/technician/build/outputs/bundle/betaRelease/*.aab $(KEY_ALIAS)
  displayName: 'Signing and aligning AAB file(s) '

- task: CmdLine@2
  inputs:
    script: >
      ls -la $(system.defaultworkingdirectory)/technician/build/outputs/bundle/betaRelease/
  displayName: 'Print output directory '

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(system.defaultworkingdirectory)/technician/build/outputs/bundle/betaRelease/'
    Contents: '**'
    TargetFolder: '$(build.artifactstagingdirectory)'
  displayName: 'Copy aab to stage directory'

- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
  displayName: 'Install Node.js'

- task: CmdLine@2
  inputs:
    script: 'npm install -g firebase-tools'
    workingDirectory: '$(Agent.ToolsDirectory)'
  displayName: 'Install firebase cli'

- task: CmdLine@2
  inputs:
    script: >
      firebase appdistribution:distribute $(build.artifactstagingdirectory)/*.aab 
      --token $(FIREBASE_TOKEN) 
      --app $(APP_ID) 
      --release-notes-file $(system.defaultworkingdirectory)/release-notes
      --groups "dev"
  displayName: 'Distribute aab' 
